# Please refer to step 4 in the Extensions Troubleshooting Document for instructions on how to obtain your Tier ID
# Please make sure your metric prefix always ends with a '|'
#This will create this metric in all the tiers, under this path
#metricPrefix: Custom Metrics|NetScaler Monitor|
metricPrefix: "Server|Component:<TIER ID>|Custom Metrics|NetScaler Monitor|"

# Configure your NetScaler ADX servers here
servers:
 - name: "" #name, host, port are mandatory.
   host: ""
   port:
   username: ""
   password: ""
   encryptedPassword: ""

#Please refer to the Password Encryption Documentation for instructions on how to configure an encryptionKey & encryptedPassword
# https://community.appdynamics.com/t5/Knowledge-Base/How-to-use-Password-Encryption-with-Extensions/ta-p/29397
encryptionKey:

numberOfThreads: 20


# Default information needs to be updated
controllerInfo:
  controllerHost: "controller"
  controllerPort: 8080
  account: "customer1"
  username: "user1"
  password: "welcome"
  encryptedPassword: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: ""
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""